### ISSUE TITLE
Bug with AsyncModulePlugin?

### ISSUE THREAD

**Issue by virajsanghvi** [NekR/async-module-loader#1]
I was trying to use this loader, but encountered this issue: https://github.com/webpack/bundle-loader/issues/17

I have a work around (caching if the module loaded myself), but after debugging, its this plugin that causes the constant refetching, presumably because you want retries after failures. Is it possible to not cause a refetch if the bundle is present?

Also, could you explain the memory leak this helps prevent?

Thanks!

**Comment by NekR** [comment]
Hi @virajsanghvi,

Do you mean it's refetched even after _successful_ load of script?

> presumably because you want retries after failures

Yes, the idea is that if chunk is failed to load, then all listeners are cleared and you can refetch it again. But of course this shouldn't be so for successfully loaded chunks.

> Also, could you explain the memory leak this helps prevent?

First of all, this is okay to not use `AsyncModulePlugin`, but if it's not used, then your callback are not cleared from the _webpack_ internal callbacks store after loading failure. This may cause cases like this:

``` js
var tree = createHeavyDOMTree();

// imagine this fails
require('async-module!./file')(function onLoad() {
 // although this code never gonna executed, this function is stuck
 // in webpack internals callbacks cache and is still "alive", so it
 // potentially has reference to |tree|, which will prevent it to be GCs,
// in other words -- memory leak
  manipulateTreeSomeWay(tree);
}, function onError() {
  // do something on fail
})
```

**Comment by NekR** [comment]
Okay, it was actually a silly a bug, I forgot to guard `onError` handler with `loaded` state so it was called anytime, even when bundle was successfully loaded. Should be fixed now (already on npm).

@virajsanghvi, thanks for your feedback and help here! If you can, please try new version and if everything is okay then I will close this one. I also tested on my project and it seems to work fine there after fix.

**Comment by NekR** [comment]
I also just implemented "de-referencing" for passed callbacks to the loader, so now it's theoretically totally safe to not use `AsyncModulePlugin` (unless you need "re-fetching" functionality).

Also added this note to readme:

> **NOTE:** memory leaks is a _rare_ case now which in theory should never happen at all. However, you may still want to use `AsyncModulePlugin` to have the ability to _re-fetch chunk after error_.
> If you **do not** plan to try loading chunks again after fail (e.g. "Cannot retrieve data. Click _here_ to try again" functionality), it's totally fine to not use `AsyncModulePlugin`.

**Comment by NekR** [comment]
I assume it's fixed now. Closing it.

@virajsanghvi Feel free to report another issues if something does not work for you. Thanks.
