### ISSUE TITLE
Always failing

### ISSUE THREAD

**Issue by ferhtgoldaraz** [NekR/async-module-loader#2]
I'm using your fork in a project. It's just what I needed, thanks for this.

But I'm having an issue, I'm always hitting the fail callback. Do the number of modules that return matter or something?

When I do this:

``` js
require.ensure(['layouts/admin/admin-layout'], function(require) {
    var component = require('layouts/admin/admin-layout');
    console.log(component);
}, 'admin');
```

I get what I expect, the exports object. But when I do this:

``` js
require('async-module?name=admin!layouts/admin/admin-layout')(

    function success(component) {
        console.log('success');
    },

    function fail() {
        console.log('fail');
    }

);
```

I always get the fail.

This is my webpack.config:

``` js
var webpack = require('webpack');
var StatsWriterPlugin = require('webpack-stats-plugin').StatsWriterPlugin;
var AsyncModulePlugin = require('async-module-loader/plugin');

var plugins = [
    new AsyncModulePlugin(),
    new StatsWriterPlugin({
        fields: null
    })
];

// if (process.env.NODE_ENV === 'production' && !Meteor.isCordova) {
//   plugins.push(new webpack.optimize.CommonsChunkPlugin('common', 'common.web.js'));
// }

module.exports = {
    entry: './entry',
    plugins: plugins,
    output: {
        chunkFilename: '[name]-[id].non-entry-chunk.web.js'
    },
    module: {
        loaders: [
            { test: /\.jade/, loader: 'template-html-loader' }
        ]
    }
};
```

Also, the network tab in chrome shows that the chunk was requested, and the response is 200 OK, with this contents (no whitespace above or below), in both scenarios. **I repeat, same response in both scenarios**. That's what's killing me:

``` js
webpackJsonp([1],{

/***/ 96:
/***/ function(module, exports, __webpack_require__) {

    /**
     * Admin Layout
     *
     * Default markup shared by all admin entry points
     */

    //===== STYLE ================================================================



    //===== JS ===================================================================



    //===== DEFINE COMPONENT =====================================================

    module.exports = MD.Vue.extend({
        template: __webpack_require__(97)
    });


/***/ },

/***/ 97:
/***/ function(module, exports) {

    module.exports = "<div class=\"admin-layout\"><p>This works as the layout for the admin stuff</p><router-view><p>this is content that can be accessed in the routed\ncomponent through the slot tag</p></router-view></div>"

/***/ }

});
//# sourceMappingURL=admin-1.non-entry-chunk.web.js.map
```

I don't really know if this is expecte behaviour and I just don't get what bundle-loader should be doing, or there's some legitimate issue going on.

Hope it's something small. Again, thanks for your fork, really nice.

**Comment by NekR** [comment]
Hi @ferhtgoldaraz, thanks for you feedback!

Loader should in this situation and it's very weird that it doesn't. Hope we'll be able to figure it out, but I will need your help here. 

First of all, can you please put a `debugger;` statement in `fail` function and check from where error is reported in call-stack? You most likely will need to enable "Async" in call-stack settings in Chrome to get all the function there since `async-loader` uses `setTimeout()` in some places. 
![image](https://cloud.githubusercontent.com/assets/1189265/11406544/7ac76536-93b6-11e5-83f6-1695fb666a2d.png)

Also some other modules like `Vue` may cause problems because they do really weird tricks to package everything, but check with `debugger` is a good start.

Thanks for reporting!

**Comment by ferhtgoldaraz** [comment]
OK, Here it goes. From top to bottom:

![image](https://cloud.githubusercontent.com/assets/2060086/11418241/8442df42-941e-11e5-81d5-18ac61d89fde.png)

![image](https://cloud.githubusercontent.com/assets/2060086/11418266/a24f944e-941e-11e5-8ee4-f49d6403d7d0.png)

![image](https://cloud.githubusercontent.com/assets/2060086/11418281/c8b64cb8-941e-11e5-85b4-3fd4f0496887.png)

![image](https://cloud.githubusercontent.com/assets/2060086/11418303/ee92d456-941e-11e5-9a83-d90bbf3ded66.png)

![image](https://cloud.githubusercontent.com/assets/2060086/11418322/0dc65276-941f-11e5-8238-a2c8d508255d.png)

**Comment by ferhtgoldaraz** [comment]
I can also give you one where the default require ensure works as expected if you wold find it useful. I can't really say I am able to read what's going on.

Note also that there is a lot more than just vue being able to cause weirdness. This is a Meteor project, without some packages that you would usually have (ecmascript, blaze), usuing a package that enables the use of webpack inside it (with some hard-coded preconfigured stuff ([code here](https://github.com/thereactivestack/meteor-webpack/blob/master/plugin/WebpackCompiler.js))...

And then vue on top of that.

I **really** hope none of that matters, :).

**Comment by NekR** [comment]
Thanks for showing screenshots! As I see, you are also using hot reloading. which didn't tested actually :(
Also I see that `require.ensure` isn't overridden by `async-module-loader`, so I guess some other loader/plugin does this too. Hope it's hot-reloading, then I will be able to fix easily. Will check it.

**Comment by ferhtgoldaraz** [comment]
Awesome. I can test it without hot reloading by simulating a production environment, but that minifies the code, so the stack traces will not be very helpful. Will do that later.

**Comment by goerwin** [comment]
Im having this issue too :cry:

**Comment by NekR** [comment]
Hi @erwingaitano, do you have this issue with hot reloading?

**Comment by goerwin** [comment]
It's not just hot reloading, it also happens after a full refresh. The chunk is loaded correctly with a 200 in the network tab but the error callback is called instead of the success one. 

PD: I started playing with webpack 2-beta and its System.import method instead of this loader and seems to work perfectly. So I guess that webpack 2 now handles this specific issue and there's no need for any bundle-loader.

**Comment by NekR** [comment]
> It's not just hot reloading, it also happens after a full refresh.

By hot reloading I meant that if it's enabled at all -- this plugin is not working.

`webpack` 2 indeed solves bundles-loading problem, so if you are using it, then you have no need in this plugin/loader.

**Comment by denich** [comment]
Hi @NekR ,
Have the same issue and it's really appears in case hot reloading enabling (same issue as on @ferhtgoldaraz 's screepnshots).
Can you help here?

**Comment by NekR** [comment]
@denich I personally don't use hot reloading, so right now I have no idea what happens where. If I'll have time, maybe I'll look into it.

**Comment by denich** [comment]
@NekR It would be nice if you do!

**Comment by NekR** [comment]
@denich @ferhtgoldaraz if it's still makes sense for you, with a new version it should now work fine with HMR. At least it won't fail anymore, but some times you may not get errors reporting because of race condition.

**Comment by ferhtgoldaraz** [comment]
The next time I try to confront this I'll try to rmemeber to comment here how it goes, thanks!
