### ISSUE TITLE
how to load the cdn file use the loader

### ISSUE THREAD

**Issue by abnerCrack** [NekR/async-module-loader#3]
i want use the loader load the remote file 
`require('async-module!http://xx.min.js')(function onLoad(mod) {
    console.log(mod)
 // mod.doSomething();
}, function onError() {
});
`
it's not working .

**Comment by NekR** [comment]
@abnerCrack hmm, I am not sure it's supposed to. Does it work with normal `bundle-loader`? Why not just load it with `<script>` element created in code?

**Comment by abnerCrack** [comment]
I ask a question in starkoverflow you can see that
http://stackoverflow.com/questions/36740281/how-to-load-remote-file-in-webpack

**Comment by NekR** [comment]
@abnerCrack you have to set `publicPath` of webpack `output` option to something like this `http://cdn.my-site.com/` and then just require file as is from code `require('my-component')`. This will load `http://cdn.my-sute.com/my-component.js`.

Try to google about `publicPath` option.

**Comment by abnerCrack** [comment]
The component is not fixed  i can't use the publicpath .but  thank you very much

**Comment by NekR** [comment]
Hmm.. let me think what I can do here.

**Comment by NekR** [comment]
Taking an example from http://webpack.github.io/docs/library-and-externals.html you probably can do this:

``` js
{ externals: { "async-module!jquery": "asyncJQuery" } }
```

which has to work as it seems to be working with `bundle-loader` (docs say so).
Anyway, this seems out of scope of this loader and probably has to be handled with webpack itself.
